### ISSUE TITLE
旧版代码呢

### ISSUE THREAD

**Issue by xu-Fencer** [FIFCOM/Pastebin#1]
原来的代码能保留吗，可以新建个仓库或者分支吗
（也可能是我太傻逼了没找到旧版本）
求教
鸽子我爱你**mua**
（诶gayhub这个md编辑器不错诶，开源吗，鸽子你找找（）

**Comment by xu-Fencer** [comment]
:heart_eyes:

**Comment by xu-Fencer** [comment]
你看还支持emoji:sweat_smile:

**Comment by xu-Fencer** [comment]
我是傻逼

**Comment by FIFCOM** [comment]
https://github.com/FIFCOM/Pastebin/releases/
